### ISSUE TITLE
Regarding GPT4 API access

### ISSUE THREAD

**Issue by ivafractal** [bichengcao/AI-Galactic-Expansion#6]
Sorry for creating this issue regardless of its relevance with this repo, I will delete this issue after your reply.

I saw your contribution to OpenAI evals repo so I was curious to know if you got the GPT4 API access.

**Comment by bichengcao** [comment]
Yes, I have GPT-4 access now. Please refer to this comment: https://github.com/openai/evals/issues/1066#issuecomment-1568804099

**Comment by ivafractal** [comment]
Thank you for replying

Have you received any email regarding that?

**Comment by bichengcao** [comment]
No, there is no email notification of GPT-4 API access granted. You need to
check the playground.

**Comment by mrunal2401** [comment]
> bichengcao

Hey, are you getting the OpenAI API access also? or only getting access for the playground and Chat-gpt??

**Comment by bichengcao** [comment]
> 

It's API access.
